### 基本操作

数组上的算术运算符会应用到元素级别，下面是创建一个新数组并填充结果的示例：

In [1]:
import numpy as np

In [2]:
a = np.array([20,30,40,50])

In [3]:
b = np.arange(4)

In [4]:
b

array([0, 1, 2, 3])

In [5]:
c = a-b

In [6]:
c

array([20, 29, 38, 47])

In [7]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [8]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [9]:
a<35

array([ True,  True, False, False])

#### 与许多矩阵语言不同，乘积运算符*在numpy中按元素进行运算。矩阵乘积可以使用@运算符（在python>=3.5中）或dot函数或方法执行：

In [10]:
A = np.array([[1,1],[0,1]])

In [11]:
B = np.array([[2,0],[3,4]])

In [13]:
A * B #元素乘积

array([[2, 0],
       [0, 4]])

In [14]:
A @ B #矩阵乘积

array([[5, 4],
       [3, 4]])

In [16]:
A.dot(B) #矩阵乘积

array([[5, 4],
       [3, 4]])

#### 某些操作（例如+=和*=）会直接更改被操作的矩阵数组而不会创建新矩阵数组。

In [17]:
a = np.ones((2,3),dtype=int)

In [18]:
b = np.random.random((2,3))

In [19]:
a *= 3

In [20]:
a

array([[3, 3, 3],
       [3, 3, 3]])

In [21]:
b += a

In [22]:
b

array([[3.66024887, 3.86291951, 3.16286273],
       [3.81895657, 3.93425076, 3.86841181]])

In [23]:
a += b #报错，b中的元素不会自动转为int类型

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

#### 当使用不同类型的数组进行操作时，结果数组的类型对应于一般或更精确的数组（称为向上转换的行为）。

In [24]:
a =np.ones(3,dtype=np.int32)

In [26]:
from numpy import pi

In [40]:
b=np.linspace(0,pi,3)

In [41]:
b

array([0.        , 1.57079633, 3.14159265])

In [42]:
b.dtype

dtype('float64')

In [43]:
c = a+b

In [44]:
c

array([1.        , 2.57079633, 4.14159265])

In [45]:
c.dtype

dtype('float64')

In [46]:
d = np.exp(c*1j)

In [47]:
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [48]:
d.dtype

dtype('complex128')

#### 许多一元操作，例如计算数组中所有元素的总和，都是作为ndarray类的方法实现的

In [49]:
a = np.random.random((2,3))

In [50]:
a

array([[0.37848123, 0.05079759, 0.17633265],
       [0.62525535, 0.9698687 , 0.48275869]])

In [51]:
a.sum()

2.683494221638054

In [52]:
a.min()

0.0507975878367809

In [53]:
a.max()

0.9698687040657507

#### 默认情况下，这些操作适用于数组，就像它是一个数字列表一样，无论其形状如何。但是，通过指定axis参数，你可以沿数组的指定轴应用操作：

In [54]:
b = np.arange(12).reshape(3,4)

In [55]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [57]:
b.min(axis=1)

array([0, 4, 8])

In [58]:
b.cumsum(axis=1) #每一行的累计和

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)