### 索引、切片和迭代

一维的数组可以进行索引、切片和迭代操作，就像列表和python序列类型一样

In [1]:
import numpy as np

In [2]:
a = np.arange(10)**3

In [3]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [4]:
a[2] #索引

8

In [5]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [6]:
a[:6:2] = -1000 #相当于a[0:6:2],从索引0开始，到索引6（不包含），步长2，替换值

In [7]:
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [8]:
a[::-1] #倒序排列

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000], dtype=int32)

In [10]:
a = np.arange(10)
for i in a:
    print(i**(1/3.))

0.0
1.0
1.2599210498948732
1.4422495703074083
1.5874010519681994
1.7099759466766968
1.8171205928321397
1.912931182772389
2.0
2.080083823051904


多维的数组每个轴可以有一个索引。这些索引以逗号分隔的元组给出：

In [11]:
def f(x,y):
    return 10*x+y

In [12]:
b = np.fromfunction(f,(5,4),dtype=int)

In [13]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [14]:
b[2,3]

23

In [15]:
b[2][3]

23

In [16]:
b[0:5,1]

array([ 1, 11, 21, 31, 41])

In [17]:
b[:,1]

array([ 1, 11, 21, 31, 41])

In [18]:
b[1:3,:]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

当提供的索引少于轴的数量时，缺失的索引被认为时完整的切片：

In [20]:
b[-1] #相当于b[-1:]

array([40, 41, 42, 43])

b[i]方括号中的表达式i被视为后面紧跟着:的多个实例，用于表示剩余轴。numpy也允许你使用三个点写为b[i,...]

三个点(...)表示产生完整索引元组所需的冒号。例如，如果x是rank为5数组（即，它具有5个轴），则：

+ x[1,2,...]相当于x[1,2,:,:,:]

+ x[...,3]等效于x[:,:,:,:,3]

+ x[4,...,5,:]等效于x[4,:,:,5,:]

In [22]:
c = np.array([[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
...                 [ 10, 12, 13]],
...                [[100,101,102],
...                 [110,112,113]]])

In [23]:
c.shape

(2, 2, 3)

In [25]:
c[1,...] #相当于c[1,:,:]或者c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [26]:
c[...,2] #相当于c[:,:,2]

array([[  2,  13],
       [102, 113]])

对多维数组进行迭代时相对于第一个轴完成的：

In [27]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


#### 但是，如果想对数组中的每个元素执行操作，可以使用flat属性，该属性时数组的所有元素的迭代器：

In [28]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43
