### 通函数

numpy提供熟悉的数学函数，例如sin,cos和exp。在numpy中，这些被称为“通函数”（ufunc）。在numpy中，这些函数在数组上按元素进行运算，产生一个数组作为输出。

In [1]:
import numpy as np

In [2]:
x = np.arange(3)

In [3]:
x

array([0, 1, 2])

In [4]:
np.exp(x) #以自然常数e为底的指数

array([1.        , 2.71828183, 7.3890561 ])

In [6]:
np.sqrt(x) #开平方

array([0.        , 1.        , 1.41421356])

In [7]:
C = np.array([2,-1,4])

In [8]:
np.add(x,C)

array([2, 0, 6])

#### np.all()

In [9]:
np.all([[True,False],[True,True]])

False

In [10]:
np.all([[True,False],[True,True]],axis=0)

array([ True, False])

In [11]:
np.all([-1,4,5])

True

In [12]:
np.all([1.0,np.nan])

True

In [13]:
np.all([0,1,3]) #元素值为0才对应false

False

In [14]:
a = np.array([1,2,3])
b = np.array([1,2,4])

In [15]:
a==b

array([ True,  True, False])

In [16]:
#为了判断两个数组是否完整一致，可以这样使用
(a==b).all()

False

In [18]:
#或者这样
np.all((a==b))

False

#### np.any()

和all正好相反

In [19]:
np.any([[True,False],[False,False]]) #有一个元素对应True，则返回的结果就是True

True

In [20]:
np.any([[True,False],[False,False]],axis=0)

array([ True, False])

In [21]:
(a==b).any()

True

#### np.apply_along_axis(func1d, axis, arr, *args, **kwargs)

将一个函数应用于一个一维的数组上（由轴决定）

In [22]:
def my_func(a):
    """计算头尾两个元素之和的平均值"""
    return (a[0]+a[-1])*0.5

In [23]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [24]:
np.apply_along_axis(my_func,0,b)

array([4., 5., 6.])

In [25]:
np.apply_along_axis(my_func,1,b)

array([2., 5., 8.])

还可以使用一些默认的函数，比如sorted进行排序

In [26]:
b = np.array([[8,1,7], [4,3,9], [5,2,6]])

In [27]:
np.apply_along_axis(sorted,1,b)

array([[1, 7, 8],
       [3, 4, 9],
       [2, 5, 6]])

#### np.argmax(a, axis=None, out=None)

返回在一个轴上最大值的索引

In [28]:
a = np.arange(6).reshape(2,3) + 10

In [29]:
a

array([[10, 11, 12],
       [13, 14, 15]])

In [30]:
np.argmax(a)

5

In [31]:
np.argmax(a,axis=0)

array([1, 1, 1], dtype=int64)

In [32]:
np.argmax(a,axis=1)

array([2, 2], dtype=int64)

In [33]:
b = np.arange(6)

In [34]:
b[1] = 5

In [35]:
b

array([0, 5, 2, 3, 4, 5])

In [36]:
np.argmax(b) #返回第一个最大值的索引

1

#### np.argmin(a, axis=None, out=None)

和argmax相反

In [ ]:
np.argsort()